<?php

namespace Database\Seeders;

use App\Models\Language;
use App\Models\LanguagePage;
use App\Models\Page;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class PagesVehiclesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        $vehicle_brands = [
            'Abarth',
            'Ac',
            'Acura',
            'Addax',
            'Adiva',
            'Adly',
            'Aeon',
            'Aiways',
            'Aixam',
            'Alfa romeo',
            'Alpina',
            'Alpine',
            'Alrendo',
            'Amc',
            'Aprilia',
            'Aro',
            'Artega',
            'Asia motors',
            'Asiawing',
            'Aston martin',
            'Atala',
            'Audi',
            'Austin',
            'Austin-healey',
            'Auto union',
            'Autobianchi',
            'Baic',
            'Baotian',
            'Barkas',
            'Baw',
            'Bedford',
            'Beeline',
            'Beijing',
            'Benelli',
            'Bentley',
            'Benzhou',
            'Bertone',
            'Bestune',
            'Beta',
            'Bimota',
            'Bitter',
            'Bizzarrini',
            'Bmw',
            'B-on',
            'Bond',
            'Borgward',
            'Bristol',
            'Brixton',
            'Bsa motorcycles',
            'Buell',
            'Bugatti',
            'Buick',
            'Byd',
            'Cadillac',
            'Cagiva',
            'Cake',
            'Callaway',
            'Carbodies',
            'Casalini',
            'Caterham',
            'Ccm',
            'Cenntro',
            'Cezeta',
            'Cf moto',
            'Citroën',
            'Checker',
            'Chery',
            'Chevrolet',
            'Chrysler',
            'Cmc',
            'Cpi',
            'Cupra',
            'Dacia',
            'Daelim',
            'Daewoo',
            'Daf',
            'Daihatsu',
            'Daimler',
            'Dallas',
            'De lorean',
            'De tomaso',
            'Derbi',
            'Dfsk',
            'Dodge',
            'Donkervoort',
            'Dr',
            'Ds',
            'Ducati',
            'E.f.o',
            'E.go',
            'Ecm',
            'Elaris',
            'Emw',
            'Energica',
            'Eton',
            'Evo',
            'Fantic',
            'Ferrari',
            'Fiat',
            'Fisker',
            'Ford',
            'Ford australia',
            'Ford otosan',
            'Ford usa',
            'Fso',
            'Gac mobylette',
            'Galloper',
            'Garelli',
            'Gasgas',
            'Gaz',
            'Geely',
            'Generic',
            'Genesis',
            'Geo',
            'Gilera',
            'Ginetta',
            'Giotti victoria',
            'Glas',
            'Gmc',
            'Goupil',
            'Govecs',
            'Great wall',
            'Harley-davidson',
            'Haval',
            'Hercules',
            'Hindustan',
            'Hmracing',
            'Hobbycar',
            'Honda',
            'Hongqi',
            'Horex',
            'Horwin',
            'Huatian',
            'Hummer',
            'Husaberg',
            'Husqvarna',
            'Hyosung',
            'Hyundai',
            'Hyundai (huatai)',
            'Ickx',
            'Indian',
            'Indigo',
            'Ineos',
            'Infiniti',
            'Innocenti',
            'Iran khodro',
            'Irmscher',
            'Isdera',
            'Iso',
            'Isorivolta',
            'Isuzu',
            'Italjet',
            'Iveco',
            'Izh',
            'Jac',
            'Jaguar',
            'Jawa',
            'Jeep',
            'Jensen',
            'Jinlun',
            'Kawasaki',
            'Keeway',
            'Kia',
            'Kreidler',
            'Ksr moto',
            'Ktm',
            'Kuba',
            'Kymco',
            'Lada',
            'Lamborghini',
            'Lambretta',
            'Lancia',
            'Land rover',
            'Landwind (jmc)',
            'Laverda motorcycles',
            'Ldv',
            'Levc',
            'Lexmoto',
            'Lexus',
            'Lifan',
            'Ligier',
            'Lincoln',
            'Lingben',
            'Livewire',
            'Lml',
            'Lotus',
            'Lti',
            'Lucid',
            'Luxxon',
            'Lynk & co',
            'Mahindra',
            'Maico',
            'Malaguti',
            'Man',
            'Marcos',
            'Maserati',
            'Mash',
            'Maxus',
            'Maybach',
            'Mazda',
            'Mbk',
            'Mclaren',
            'Mega',
            'Megelli',
            'Mercedes-benz',
            'Metrocab',
            'Mg',
            'Mia electric',
            'Micro',
            'Microcar',
            'Middlebridge',
            'Minelli',
            'Mini',
            'Mitsubishi',
            'Mitsuoka',
            'Mondial',
            'Morgan',
            'Morris',
            'Moskvich',
            'Moto guzzi',
            'Motobi',
            'Moto-morini',
            'Motowell',
            'Motron',
            'Mpm motors',
            'Mv agusta',
            'Mz',
            'Nio',
            'Nipponia',
            'Nissan',
            'Niu',
            'Nsu',
            'Oldsmobile',
            'Oltcit',
            'Online',
            'Opel',
            'Ora',
            'Osca',
            'Panoz',
            'Panther',
            'Peugeot',
            'Pgo motorcycles',
            'Piaggio',
            'Pininfarina',
            'Plymouth',
            'Polestar',
            'Pontiac',
            'Porsche',
            'Premier',
            'Proton',
            'Puch',
            'Qingqi',
            'Qjmotor',
            'Quadro',
            'Ram',
            'Ranger',
            'Rayton fissore',
            'Regal raptor',
            'Reliant',
            'Renault',
            'Renault trucks',
            'Rex',
            'Riley',
            'Rivero',
            'Rolls-royce',
            'Rover',
            'Royal enfield',
            'Ruf',
            'Saab',
            'Sachs',
            'Samsung',
            'Sanben',
            'Sanglas',
            'Santana',
            'Scomadi',
            'Seat',
            'Seres',
            'Sevic',
            'Sfm',
            'Shelby',
            'Sherco',
            'Shineray',
            'Simson',
            'Sipani',
            'Skoda',
            'Skywell',
            'Smart',
            'Solo',
            'Sommer motorcycles',
            'Spectre',
            'Sportequipe',
            'Spyker',
            'Ssangyong',
            'Standard automobile',
            'Steyr',
            'Streetscooter',
            'Subaru',
            'Super soco',
            'Suzuki',
            'Swm',
            'Swm motors',
            'Sym',
            'Talbot',
            'Tata',
            'Tazzari',
            'Tesla',
            'Tgb',
            'Think',
            'Tinbot',
            'Togg',
            'Tomos',
            'Tornax',
            'Toyota',
            'Trabant',
            'Triumph',
            'Tropos',
            'Turbho',
            'Tvr',
            'Uaz',
            'Um',
            'Umm',
            'Vauxhall',
            'Vector',
            'Vento',
            'Vertigo',
            'Vespa',
            'Victory motorcycles',
            'Vinfast',
            'Voge',
            'Volvo',
            'Vw',
            'Wangye',
            'Wartburg',
            'Westfield',
            'Wey',
            'Wiesmann',
            'Wolseley',
            'Xbus',
            'Xev',
            'Xgjao',
            'Xingyue',
            'Xpeng',
            'Yadea',
            'Yamaha',
            'Yiben',
            'Yugo',
            'Yulon',
            'Zastava',
            'Zaz',
            'Zd',
            'Zero',
            'Znen',
            'Zongshen',
            'Zontes',
            'Zuendapp',
        ];

        $languages = Language::all();
        foreach($vehicle_brands as $vehicle_brand){
            $page = new Page();
            $page->parent_id = null;
            $page->type = 'vehicle';
            $page->show_in_pages = 1;
            $page->save();

            foreach($languages as $language){
                $language_page = new LanguagePage();

                $language_page->page_id = $page->id;
                $language_page->language_id = $language->id;
                $language_page->type = $page->type;
                $language_page->name = $vehicle_brand;
                $language_page->slug = Str::slug($vehicle_brand, "-");
                $language_page->save();
            }
        }
    }
}
